### ISSUE TITLE
Min/Max penalties too strong?

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#249] opened 2017-12-08 22:29 UTC
When I recently made a new character, I considered putting a 1 in a stat. I wanted a more challenging character. However, when I looked over the list of stats, I felt that STR/PER/CHA penalties are too strong. If the penalties are too strong, hardly anyone will consider it an option because it isn't much fun to play the game as a vegetable --the penalties effectively bar usage. 
Here is the current list of debilitations:

- Strength: If you have 1 Strength, you are exceptionally weak and your max movement per 2 actions is 2m (unless your Dex is 1) and you cannot wear armor that offers more than 50% coverage.
- Perception: If you have 1 Perception, you are partially blind, only have 1 eye, or something similar. You cannot use the Search or Awareness skills and you have a -20 malus to Speech skill rolls. 
- Fortitude: If you have 1 Fortitude, you are exceptionally frail. You can't inflict lethal 	unarmed damage and your unarmed damage is halved. Also, when you deal melee damage, 	you inflict half of the damage on yourself.
- Charisma: If you have 1 Charisma, you have a debilitating speech impediment. You have an additional malus of -24 when using Speech, Deceive, and etc. skill. Under normal circumstances, you have to succed a DC 30 CHA skill check in order to communicate with a non-player character (NPC). In combat, vocal communication to anything costs 1 Action.
- Intelligence: If you have 1 intelligence, let's just say, you aren't particularly smart. You cannot attempt to use any skill that you do not have Proficiency in (see the 	"RP / Using Skills" section).
- Dexterity: If you have 1 Dexterity, you are especially clumsy or suffer from a debilitating	illness which affects your ability to move swiftly and precisely. You cannot learn any skills that use Dexterity as the contributing stat (for example, lockpicking).
- Luck: If you have 1 Luck, it goes without saying, you are very unlucky. At the start of a combat encounter, roll a d10 and receive a penalty from the Black Cat table, below.	

I recommend changing a few of these to the following:

- Strength: If you have 1 Strength, you are exceptionally weak. You cannot throw weapons more than 
	10m, and you cannot wear armor that offers more than 50% coverage.
- Perception: If you have 1 Perception, you are partially blind, only have 1 eye, or something similar. You cannot use the Search or Awareness skills and you have an additional -4 to your PER mod. 
- Charisma: If you have 1 Charisma, you have a debilitating speech impediment. You have an additional  -14 to your CHA Mod. Under normal circumstances, you have to succeed a DC 20 CHA skill check in order to communicate with a non-player character (NPC).

**Comment by bleehu** [comment] 2017-12-11 22:09
I recommend not making any of these changes. Heavily penalizing min-maxing is good for the way Player Characters interact with each other.

**Comment by 1sourcecontrol** [comment] 2017-12-12 00:14
@bleehu can you expound on how "Heavily penalizing min-maxing is good for ..."? 

If it is any help, I will expound on my reasoning, below.

I believe min-maxing should be penalized more heavily than a given stat already does (hence my edits above). However, (as in the discussion of #114) if a stat is extremely penalized when it is at 1: "if the characters are forced to be in some smaller range, why does a wider range even exist." Here's why I think the current system needs to be changed:

1. If I take Strength = 1 that forces my movement speed to be 2, which hamstrings the usefulness of DEX. The reason DEX = 1 penalties are so small (not learning dex skills) is because DEX = 1 movement is, as far as I can tell, already a harsh enough penalty as it is. Thus, STR =1 and penalizing movement is a huge double penalty. 

2. Without the limitation to movement speed, Strength = 1 already forces you to only use melee weapons or pistols (with a weapon mod that reduces the pistol's STR requirement). This forces the player out of being useful in Martial class roles except perhaps gunslinger. Taking reasonable advantage of a  specialist/soldier/marksman/hunter/assassin class requires one or more of the following: using a weapon type that their class enables, being tanky, and moving so as to hit targets or get into cover.

3. Moving slowly inhibits game pacing and/or may require that a character be drug around on a stretcher. This may be fine in a given campaign. Maybe the DM/Player want's one of the characters to not have legs. But designing the system to especially make players lame when the system doesn't have to, seems unnecessarily excessive (i.e., both STR and DEX forcing a character to have limited movement). Why not leave it as DM/player flavor choice? 

4. Having 1 perception is a base of -16% to all ranged combat rolls and perception checks. I think the overlap into speech is unnecessarily excessive since CHA would dutifully cover that ability. Why can't I build a hero that is blind but charismatic? Seems to run against one of our armatures.

5. CHA causing limitations to actions taken in combat, as well as severe RP limitations, seems excessive to me. If I am mute or have a stutter, I could use hand-signals in combat. Adding action limitations to combat also limits the fun you can have coordinating with other players, or taking normally free actions. In C2.0 I added in a limitation to CHA skills based on your CHA level. If a player has 1 charisma, the max speech skill they can acquire is 20. Allowing some speech skill signifies a character's ability to learn how to work on overcoming their speech impediment. In the proposed CHA limitation, a CHA = 1 player with speech skill @ 20 will have a net -10% mod when using speech. And they still have to overcome a 50/50 chance of not being able to speak to an NPC at all (-16% CHA - 14% penalty = -30% CHA mod with a DC 20 CHA check).

**Comment by Turtlelord26** [comment] 2017-12-12 05:48
What I'm reading here is that you think that the given penalties for the most extreme min-max we allow are too harsh and actively inhibit gameplay in ways that aren't fun. Since a lot of what we've been doing has been focusing on making things not un-fun, this is a reasonable stance.

However:

In the particular case of primary character attributes, a few notable factors apply.
First, simply translating our scale to remove the possibility of players minning as hard as they currently can doesn't work because those people exist. Our stat system describes an extraordinary member of a population (a PC), members of which (PCs or NPCs) may naturally have a stat at 1. Because many kinds of real people exist, we are obliged to use a scale capable of describing as many as the exigencies of complexity creep permit.
Second, one of the more effective ways that humans learn is by failing spectacularly. It's almost as effective to just provide the opportunity to fail spectacularly, *and make it obvious that that is what it is*. The horrific penalties for dropping multiple stats to 1 are a subliminal lesson in not taking your extreme too far. If we shrink the scale, we risk sending the message to those prone to min-maxing that it's ok to push a system as far as it will go, which doesn't work in most places.
Third, just because of the balance-fun relationship, min-maxers can't be too much better than people who build statlines for pure RP. That's un-fun for the people who are there most of anyone for fun.

PS. Please don't throw my arguments back at me as an advocation for implementing negative skill points. Exigencies of complexity creep and all that.

**Comment by 1sourcecontrol** [comment] 2017-12-12 19:22
Good points. I appreciate the insights.

1. On the first point, correct me if I'm wrong, but it sounds like you are emphasizing realism in the stat system? A while ago, trowl223 mentioned the design of a stat at '0' being a disability/severe impairment whereas a '1' is 'moderate' impairment. I think what trowl223 said may be reasonable because having the full possibility space, where you can play a fully disabled character, may not be any fun for a given person or perhaps the other people in their campaign. 
2. On the second point, that's quite interesting. Quite frankly, I don't know where I stand on that. But I think it would be fun and interesting to allow a blind assassin, a mute hacker, or dumb but charismatic warrior. 
3. I'm definitely with you there.

__TL;DR__ _(for my thoughts on the whole discussion)_
I think it's fair that we give larger penalties (larger than I suggested) to minimized stats; however, I think the overlap between stats lowers player choice too much. Perception affects perception rolls but now, all of the sudden, when you minimize perception it affects Charisma skills as well. Same with Strength affecting Dex's movement. I think the stats should be more isolated e.g., a 1 in PER is a severe detriment only to PER mod and/or PER abilities (otherwise I can't be a blind charismatic man).

P.S. Yeah, I wouldn't want to enter the realm of negative skill points lol.

**Comment by 1sourcecontrol** [comment] 2018-01-15 18:47
@bleehu are you intending to make a reply to this when you get a chance? 

>I recommend not making any of these changes. Heavily penalizing min-maxing is good for the way Player Characters interact with each other.

Your vague reply is frustrating when I put in a good effort to make a detailed discussion of thought. 
But if you are intending to reply but don't have the time due to other pressing issues, all is well.

**Comment by bleehu** [comment] 2018-01-16 21:19
Indeed I was planning on making a much more detailed reply. I apologize that it took me this long to get to it. 
Before I continue, can I ask for some clarification? If I'm reading this right, it seems to me the root cause of the issue is that the penalties for minimizing PER and STR (and maybe a couple of others) are entangled with other stats. 
That root problem is causing the symptom that penalties for minimizing certain stats are too severe. 
If we separate each stat's penalty to be within its own paradigm of effect, then we could balance each on its own merits without the added complexity of minimizing PER affecting CHA?
Am I picking up what you're laying down? Or am I still confused?

**Comment by 1sourcecontrol** [comment] 2018-01-17 18:33
Okay, thanks!

I think you are getting what I'm saying. My focus is primarily on the overlap introduced when a primary stat equals 1 and secondarily, the general strength of the min' penalties.

**Comment by bleehu** [comment] 2018-01-17 21:18
I propose we un-overlap the penalties and keep the penalty for min-maxing aggressively fairly high. 

What say ye, men?

**Comment by 1sourcecontrol** [comment] 2018-01-22 18:59
Sounds fair. 

However, I'm still quite opposed to Charisma's, "In combat, vocal communication to anything costs 1 Action."

**Comment by bleehu** [comment] 2018-01-22 20:40
Ya, I'm not a huge fan of that particular implementation either. I like what it was trying to do, but I think it can be done better.
I kinda like the house rule that has been used before where a character with low charisma needs to make a charisma check to make themselves understood, but I don't think that's enough of a penalty on its own.

**Comment by Turtlelord26** [comment] 2018-01-22 20:48
Add disadvantage on all opposed checks where the opponent is using Cha to capture the lack of force of personality? Auto-fail is also an option if you want more harshness.

**Comment by 1sourcecontrol** [comment] 2018-01-30 16:57
@bleehu, isn't that charisma penalty already in the rules? " Under normal circumstances, you have to succeed a DC 30 CHA skill check in order to communicate with a non-player character (NPC)."
We could change it to include any player, not just NPCs. That would be pretty harsh.

Couple the charisma check with serious CHA related penalties, and that player will need their hand held through dialog -- which is what we want, I believe. *The more CHA restrictive feats we add, the more the min-maxer will be penalized, as well*

I like what @Turtlelord26  brought up about disadvantage on all opposed checks. I don't think I would want that player to have serious (dice) maluses and disadvantage tho.

**Comment by bleehu** [comment] 2018-02-01 20:59
Since there is still trepidation about how to handle each penalty, I recommend that we make a pull request per penalty, so that hangups over charisma don't prevent the progress of fixing strength.

**Comment by bleehu** [comment] 2018-06-28 20:07
@Turtlelord26, now that we've shipped a penalty for having 1 luck and 1 cha, can we close this one out?

**Comment by Turtlelord26** [comment] 2018-07-02 05:56
Looks like the proposed alternative to min penalties is elsewhere, so it doesn't look like this meta-issue is doing anything anymore. I concur.

**Closed as completed by Turtlelord26** 2018-07-02 05:56 UTC
Labels: Greenlit - Awaiting Pull Request, Priority - Med
